### ISSUE TITLE
Keyboard problem

### ISSUE THREAD

**Issue by SalvatoreAD** [huangboju/SwiftySTPopup#1]
I have problems when the keyboard appears. I created a MTPopup (bottomsheet) with a textfield at the top. When the keyboard appears, the view goes up. Can I block this movement?

**Comment by huangboju** [comment]
Sorry, temporarily can not, I will give you an interface

**Comment by huangboju** [comment]
@SalvatoreAD Sorry, temporarily can not, I will give you an interface

**Comment by SalvatoreAD** [comment]
What interface?

**Comment by huangboju** [comment]
You can use `autoAdjustKeyboardEvent`  to close the keyboard event

**Comment by SalvatoreAD** [comment]
thanks :)
